name: Publish to RapidAPI

on:
  push:
    branches: [main]
    paths:
      - 'docs/openapi.yaml'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RapidAPI/create_or_update_rapidapi_listing@main
        with:
          x_rapidapi_key: ${{ secrets.RAPIDAPI_KEY }}
          x_rapidapi_graphql_host: graphql.rapidapi.com
          graphql_url: https://graphql.rapidapi.com/
          owner_id: leandroclf
          spec_path: docs/openapi.yaml
